drop table if exists `Users`;
create table Users (
	`id`                int not null primary key auto_increment comment '递增ID',
  `name`		          varchar(30) not null comment '姓名',
	`student_id`        varchar(255) not null comment '学号',
	`sex`               varchar(30) not null default '' comment '性别: 男 女',
	`id_card`		        varchar(255) not null default '' comment '身份证',
	`password`	        varchar(255) not null comment '密码',
	`account_location` 	varchar(255) not null default '' comment '户口所在地',
	`tel_num` 	        varchar(255) not null default '' comment '电话号码',
	`is_dorm` 	        varchar(30) not null default '' comment '否 是',
	`is_create_file`    varchar(30) not null default '' comment '是否建档立卡贫困户 否 是',
	`is_subsistence`    varchar(30) not null default '' comment '是否低保户 否 是',
	`is_disability`     varchar(30) not null default '' comment '是否残疾生 否 是',
	`address` 	        varchar(255) not null default ''  comment '家庭住址',
	`graduated_school` 	varchar(255) not null default '' comment '毕业学校',
	`guardian_name` 	  varchar(30) not null default '' comment '监护人姓名',
	`guardian_tel_num` 	varchar(255) not null default '' comment '监护人电话号码',
	`guardian_id_card` 	varchar(255) not null default '' comment '监护人身份证',
	`first_subject`     varchar(30) not null default '' comment '科目信息一',
	`second_subject`    varchar(30) not null default '' comment '科目信息二',
	`created_at` 				timestamp not null DEFAULT CURRENT_TIMESTAMP comment '创建时间',
	`updated_at` 				timestamp not null DEFAULT CURRENT_TIMESTAMP comment '更新时间',

	key `name` (`name`),
	key `student_id` (`student_id`),
	key `sex` (`sex`),
	key `id_card` (`id_card`),
	key `password` (`password`),
	key `account_location` (`account_location`),
	key `tel_num` (`tel_num`),
	key `is_dorm` (`is_dorm`),
	key `is_create_file` (`is_create_file`),
	key `is_subsistence` (`is_subsistence`),
	key `is_disability` (`is_disability`),
	key `address` (`address`),
	key `graduated_school` (`graduated_school`),
	key `guardian_name` (`guardian_name`),
	key `guardian_tel_num` (`guardian_tel_num`),
	key `guardian_id_card` (`guardian_id_card`),
	key `first_subject` (`first_subject`),
	key `second_subject` (`second_subject`),
	key `created_at` (`created_at`),
	key `updated_at` (`updated_at`)
) engine=innodb default charset=utf8 collate=utf8_general_ci comment='用户信息';